const productList =  [
    {
      id: 1,
      name: "LAPTOP",
      category: "Electronic devices",
      price: 828,
      stock: 25,
    },
    {
      id: 2,
      name: "2 Color T-Shirt",
      category: "Hats",
      price: 144,
      stock: 43,
    },
    {
      id: 3,
      name: "Polo Tshirt",
      category: "Men's cloths",
      price: 28,
      stock: 123,
    },
    {
      id: 4,
      name: "Couple Set",
      category: "Men's cloths",
      price: 85,
      stock: 33,
    },
    {
      id: 5,
      name: "Collection",
      category: "Collection",
      price: 113,
      stock: 11,
    },
    {
      id: 6,
      name: "Balt Bag",
      category: "Collection",
      price: 28,
      stock: 123,
    },
    {
      id: 20,
      name: "T-Shirt",
      category: "Cloths",
      price: 25,
      stock: 10,
    },
    {
      id: 7,
      name: "Female Polo T-Shirt",
      category: "Women's cloths",
      price: 92,
      stock: 323,
    },
    {
      id: 8,
      name: "TELEPORTER",
      category: "Machine",
      price: 35,
      stock: 52,
    },
    {
      id: 9,
      name: "Duffle bag",
      category: "Accessories",
      price: 13,
      stock: 25,
    },

    {
      id: 10,
      name: " FramelessGlasses",
      category: "Glases",
      price: 828,
      stock: 30,
    },
    {
      id: 11,
      name: "Nike hat",
      category: "Hats",
      price: 144,
      stock: 20,
    },
    {
      id: 12,
      name: "COMET Shoes",
      category: "Shoes",
      price: 28,
      stock: 19,
    },
    {
      id: 13,
      name: "Rayban glasses",
      category: "Glasses",
      price: 85,
      stock: 30,
    },
    {
      id: 14,
      name: "POLO T-Shirt",
      category: "T-Shirts",
      price: 113,
      stock: 75,
    },
    {
      id: 15,
      name: "Flip-Flops",
      category: "Shoes",
      price: 28,
      stock: 12,
    },
    {
      id: 16,
      name: "Sack",
      category: "Accessories",
      price: 25,
      stock: 13,
    },
    {
      id: 17,
      name: "JOOTA",
      category: "Shoes",
      price: 92,
      stock: 18,
    },
    {
      id: 18,
      name: "ADIBOS T-Shirt",
      category: "T-Shirts",
      price: 35,
      stock: 27,
    },
    {
      id: 19,
      name: "BVLGRI Pants",
      category: "Pants",
      price: 13,
      stock: 43,
    },
  ];

  export default productList;